export const CHECK_NODE_STATUS_START = 'CHECK_NODE_STATUS_START';
export const CHECK_NODE_STATUS_SUCCESS = 'CHECK_NODE_STATUS_SUCCESS';
export const CHECK_NODE_STATUS_FAILURE = 'CHECK_NODE_STATUS_FAILURE';

// Get Node Blocks
export const GET_NODE_BLOCKS_START = 'GET_NODE_BLOCKS_START';
export const GET_NODE_BLOCKS_SUCCESS = 'GET_NODE_BLOCKS_SUCCESS';
export const GET_NODE_BLOCKS_FAILURE = 'GET_NODE_BLOCKS_FAILURE';
